language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: sOeLsGBVf8oSGfXCOOqwsisaIuhaXqwyXhPkAZUbNl5F59HIikoLosws8pxLvHBBVAWFS8ygIsgZmjypSVN9+uN5oBryT/r7OJZ+CZ1uLrhOFrn65lheV7AN6Op0yGBd8YVzINuJu6SfUzZ0eoia7Zx5W2R21WSkCZB+jrpinngPRG9VsZXwlcWab9ffyFV1iqbhC9AJMJzCBgY1t6vVewputeG49zWOuE+1JH3eYVN7jT18K53lhJ7GwiDd4FOEM0yd668xhFmI2YYvI80rDh4dtUp/nqDxWS5YJsYU0S0blxPiGrWkQBNLWrD+aYpNk/uQ8xcnz4FS09MtmdGk3D7JLlNoBn4fB2VR08ErPGI1Yoe+SlHLdZDIdTHRqUU5NPEyiFbkZaXDrL6uGFbhcuRlpHvOHjePQ85YXx3eoXhn9Y/Jq9qTXVwsVUXSWXcdCIYXBTtUVa/rLHhlK3PSObvp4Z+mGgfY0YJJTz5fOt6zEF107Y1MZu5qXpmgGGPNaCZfCAchlHXz4PEUZhc978ZORrIlz+l2qbhDgvcyXb907SE4ZVvlOEEOKUcy3IE7bvi1LawjfgB4t/1SQV81iZu/0uHlorNwkyyb+s0m2NVKBkPZxVCKP8vrGjSB4yNhA9bPsCw7hJEGhUpzi6CUDRw9oHnH5PCc8XxpcEKlNH0=
